# Generated by Django 6.0.2 on 2026-04-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_prompt_generations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTextGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('response_message', models.TextField()),
                ('response_done', models.CharField(max_length=255)),
                ('response_done_reason', models.CharField(max_length=255)),
                ('response_total_duration', models.CharField(max_length=255)),
                ('response_load_duration', models.CharField(max_length=255)),
                ('response_prompt_eval_count', models.CharField(max_length=255)),
                ('response_prompt_eval_duration', models.CharField(max_length=255)),
                ('response_eval_count', models.CharField(max_length=255)),
                ('response_eval_duration', models.CharField(max_length=255)),
                ('ai_prompt_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_text_generations', to='ai_prompt_generations.aipromptgeneration')),
            ],
            options={
                'verbose_name': 'AiTextGeneration',
                'verbose_name_plural': 'AiTextGenerations',
            },
        ),
    ]
