# Generated by Django 6.0 on 2025-12-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ollama_texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_prompt', models.CharField(blank=True, max_length=200, null=True)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('nonce', models.CharField(max_length=100)),
                ('sampler_index', models.IntegerField()),
                ('cfg_scale', models.FloatField()),
                ('seed', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('image_base', models.ImageField(upload_to='images')),
                ('ollama_text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ollama_texts.ollamatext')),
            ],
            options={
                'verbose_name': 'singular',
                'verbose_name_plural': 'plural',
            },
        ),
    ]
