# Generated by Django 6.0 on 2026-01-04 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ollamaimage',
            name='image_base',
        ),
        migrations.AddField(
            model_name='ollamaimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ollamaimage',
            name='image_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ollamaimage',
            name='image_mime',
            field=models.CharField(default='image/png', max_length=50),
        ),
        migrations.AddField(
            model_name='ollamaimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
