# Generated by Django 6.0 on 2026-01-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama_images', '0002_remove_ollamaimage_image_base_ollamaimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ollamaimage',
            name='sampler_index',
            field=models.CharField(max_length=200),
        ),
    ]
