# Generated by Django 6.0.2 on 2026-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comfyui_prompt_id', models.CharField(max_length=255)),
                ('comfyui_output_path', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AiImageGeneration',
                'verbose_name_plural': 'AiImageGenerations',
            },
        ),
    ]
