# Generated by Django 6.0.2 on 2026-04-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_image_generations', '0001_initial'),
        ('ai_prompt_generations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimagegeneration',
            name='ai_prompt_generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_image_generations', to='ai_prompt_generations.aipromptgeneration'),
        ),
    ]
