# Generated by Django 6.0 on 2025-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ollama',
            options={'verbose_name': 'ollama', 'verbose_name_plural': 'ollamas'},
        ),
        migrations.AddField(
            model_name='ollama',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
