# Generated by Django 6.0 on 2025-12-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_ollama_options_ollama_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ollama',
            name='request_prompt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ollama',
            name='response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
