# Generated by Django 6.0.2 on 2026-04-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_prompt_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPromptGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('system_role', models.CharField(max_length=255)),
                ('system_message', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
                ('user_message', models.CharField(max_length=255)),
                ('is_text_processed', models.BooleanField(default=False)),
                ('is_image_processed', models.BooleanField(default=False)),
                ('is_video_processed', models.BooleanField(default=False)),
                ('ai_prompt_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_generations', to='ai_prompt_categories.aipromptcategory')),
            ],
            options={
                'verbose_name': 'AiPromptGeneration',
                'verbose_name_plural': 'AiPromptGenerations',
            },
        ),
    ]
